# Generated by Django 3.0.1 on 2022-03-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220323_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='62640', max_length=200, null=True, unique=True),
        ),
    ]
