# Generated by Django 3.0.1 on 2022-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220324_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='57260', max_length=200, null=True, unique=True),
        ),
    ]
