# Generated by Django 3.0.1 on 2022-03-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220327_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='48946', max_length=200, null=True, unique=True),
        ),
    ]
