# Generated by Django 3.0.1 on 2022-03-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220328_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='20897', max_length=200, null=True, unique=True),
        ),
    ]
